//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_dbEntities : DbContext
    {
        public student_dbEntities()
            : base("name=student_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student> Students { get; set; }
        public DbSet<Cours> Courses { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<StudentCours> StudentCourses { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
